### ISSUE TITLE
报错“当前版本过低，请先升级到手机QQ最新版本”

### ISSUE THREAD

**Issue by holk-h** [ForteScarlet/simple-robot-core#7]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.simbot.component.mirai.MiraiBotInfo.<init>(MiraiBots.kt:209)
	at com.simbot.component.mirai.MiraiApplication.verifyBot(MiraiApplication.kt:310)
	... 10 more

**Comment by ForteScarlet** [comment]
大概率是由于QQ账号被封、密码错误等原因，请检查账号情况以及密码正确性。
小概率是由于异地登录、QQ登录验证超时等原因，请多尝试几次并注意观察是否存在相应的提示。
此为Mirai登录时抛出的异常，其他相关内容可查看mirai的issue [#628](https://github.com/mamoe/mirai/issues/628)

**Comment by holk-h** [comment]
> 大概率是由于QQ账号被封、密码错误等原因，请检查账号情况以及密码正确性。
> 小概率是由于异地登录、QQ登录验证超时等原因，请多尝试几次并注意观察是否存在相应的提示。
> 此为Mirai登录时抛出的异常，其他相关内容可查看mirai的issue [#628](https://github.com/mamoe/mirai/issues/628)

已解决，感谢

**Comment by hswyxj** [comment]
14:17:06 [INFO] [NETWORK] Send: wtlogin.login
 14:17:07 [INFO] [NETWORK] Recv: Error(title=温馨提示, message=当前版本过低，请
先升级到手机QQ最新版本。, errorInfo=

我也遇到了   改了密码也还是报这个，账号没有被被封、没有异地登录

**Comment by ForteScarlet** [comment]
> 14:17:06 [INFO] [NETWORK] Send: wtlogin.login
> 14:17:07 [INFO] [NETWORK] Recv: Error(title=温馨提示, message=当前版本过低，请
> 先升级到手机QQ最新版本。, errorInfo=
> 
> 我也遇到了 改了密码也还是报这个，账号没有被被封、没有异地登录

参考mirai [#621](https://github.com/mamoe/mirai/issues/621), 并排查一下其他可能的账号异常因素，密码错误、账号异常等。

**Comment by ForteScarlet** [comment]
> 14:17:06 [INFO] [NETWORK] Send: wtlogin.login
> 14:17:07 [INFO] [NETWORK] Recv: Error(title=温馨提示, message=当前版本过低，请
> 先升级到手机QQ最新版本。, errorInfo=
> 
> 我也遇到了 改了密码也还是报这个，账号没有被被封、没有异地登录

也可以参考 [文档-mirai组件注意事项](https://www.yuque.com/simpler-robot/simpler-robot-doc/rx111k#xKysr) ，尝试切换mirai协议为**安卓手机**
